# Minecraft Backup Manager Configuration

# Docker container name running the Minecraft server
container_name: "minecraft-mc-1"

# Paths to the world directories inside the container
world_paths:
  - "/data/world"
  - "/data/world_nether"
  - "/data/world_the_end"

# Local backup directory
backup_dir: "./backups"

# Warning times in minutes before shutdown
warnings:
  - 15
  - 10
  - 5
  - 1

# Retention policy
retention:
  # Maximum number of backups to keep (set to 0 to disable)
  max_backups: 7
  # Maximum age of backups in days (set to 0 to disable)
  max_days: 14

# Development mode
# Set to true to only test send_server_command and exit
# Set to false for normal operation
dev: true
